### ISSUE TITLE
Don't work in Laravel 5.5

### ISSUE THREAD

**Issue by massiws** [atomescrochus/laravel-bulma-starter#5]
I'm trying to install in Laravel 5.5 via composer:
```
composer require atomescrochus/laravel-bulma-starter
```
I get this error:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

                                                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Class 'Atomescrochus\LaravelBulmaStarter\LaravelBulmaStarterServiceProvider  
  ::class,' not found
```
The same manually editing `composer.json` and `config/app.php` and running `composer update`

Same steps in Laravel 5.4.* with no errors.

Any tips?

**Comment by ekandreas** [comment]
I can confirm the same error/issue

**Comment by massiws** [comment]
Maybe, can it be related to [this](https://github.com/laravel/internals/issues/784) issue?

Temporarly, I solved adding the dependency in `require` and removing the `post-autoload-dump` entry in `composer.json`:
```
    "require": {
        ...
        "atomescrochus/laravel-bulma-starter": "^2.1",
       ...
  "post-autoload-dump": []
```

**Comment by jpmurray** [comment]
I'll have to check in the coming days when I have spare time. My own tests worked if I remember correctly, but I might have made a typo somewhere? We'll see.

Honestly, this package will have to get deprecated at some point though, since there is probably a way to hook in 5.5's frontend presets... ?

**Comment by jpmurray** [comment]
Oh wait. I see @massiws that it tried to call `@php artisan package:discover`. The `@` makes the command not fire. If you remove it in your `composer.json`, it will correctly fire the discover feature.  

(I'm getting this problem every time I `laravel new` something, since it does not copy the .env file because of it.)

@ekandreas could you try that too?

**Comment by massiws** [comment]
@jpmurray, I've just tried to remove `@` sign from `composer.json`: same problem.

**Comment by jpmurray** [comment]
Just pushed `2.1.1` to address this issue (I had the same problem on other package, it was a mistake on my part). If anything else, don't hesitate to reopen the issue.
